export const theme = {
  token: {
    colorPrimary: '#ccac85',
    colorInfo: '#ccac85',
    wireframe: false,
    // colorTextBase: "#383533",
    colorBgBase: '#fbfbfb',
    colorLink: '#8e5f40',
    fontSizeHeading1: 20,
    fontSizeHeading2: 18,
    fontSizeHeading3: 16,
    fontSizeHeading4: 14,
    fontSizeHeading5: 14,
    sizeStep: 4,
    sizeUnit: 4,
    colorTextBase: '#61605f',
    colorText: '#383533',
    colorTextSecondary: '#61605f',
    colorTextTertiary: '#969390',
    colorTextQuaternary: '#c7c4c2',
    colorBorder: '#f0eeec',
    colorBorderSecondary: '#f0eeec',

    colorSuccess: '#61c28f',
    colorSuccessBg: '#ebfae9',
    colorSuccessBorder: '#d8f4da',
    colorWarning: '#8e5f40',
    colorWarningBorder: '#f6edd4',
    colorWarningBg: '#fdfaf3',
    colorError: '#ec7d57',
    colorErrorBorder: '#ffe0d3',
    colorErrorBg: '#fff2ec',
  },
  components: {
    Select: {
      optionSelectedBg: 'rgb(249,246,240)',
      optionActiveBg: 'rgb(243,237,225)',
      colorBgContainerDisabled: '#F3F3F3',
      colorTextDisabled: '#61605F',
      controlHeightLG: 36,
      controlHeight: 32,
      controlHeightSM: 28,
      borderRadiusLG: 6,
      borderRadius: 6,
      borderRadiusSM: 6,
      fontSize: 14,
      fontSizeLG: 14,
      fontSizeSM: 14,
      selectorBg: '#fff',
    },
    Progress: {
      colorText: '#ccac85',
    },
    Menu: {
      subMenuItemBg: 'rgb(255,255,255)',
      itemHoverBg: 'rgb(243,237,225)',
      itemHoverColor: 'rgb(94,65,48)',
      itemSelectedColor: 'rgb(94,65,48)',
      itemSelectedBg: 'rgb(249,246,240)',
      groupTitleColor: 'rgb(97,96,95)',
    },
    Button: {
      colorBgContainerDisabled: 'rgb(230,217,194)',
      colorTextDisabled: 'rgb(255,255,255)',
      borderColorDisabled: 'rgb(230,217,194)',
      colorPrimaryBgHover: 'rgb(184,137,86)',
      colorPrimaryHover: 'rgb(184,137,86)',
      paddingInline: 20,
      paddingBlock: 7,
      paddingInlineLG: 22,
      paddingBlockLG: 10,
      paddingInlineSM: 16,
      paddingBlockSM: 5,
      borderRadius: 6,
      borderRadiusLG: 6,
      controlHeightLG: 36,
      controlHeight: 32,
      controlHeightSM: 28,
      contentFontSizeLG: 16,
      defaultBorderColor: 'rgb(243,237,225)',
      defaultBg: 'rgb(243,237,225)',
      defaultColor: 'rgb(142,95,64)',
      defaultHoverBg: 'rgb(230,217,194)',
      defaultHoverBorderColor: 'rgb(230,217,194)',
      defaultHoverColor: 'rgb(142,95,64)',
      defaultActiveBorderColor: 'rgb(214,191,155)',
      defaultActiveBg: 'rgb(214,191,155)',
      defaultActiveColor: 'rgb(142,95,64)',
      ghostBg: 'rgb(255,255,255)',
      defaultGhostColor: 'rgb(184,137,86)',
      defaultGhostBorderColor: 'rgb(226,223,221)',
    },
    Checkbox: {
      paddingXS: 6,
      colorBorder: '#C7C4C2',
      colorBgContainer: '#fff',
      colorBgContainerDisabled: '#F0F0F0',
      colorTextDisabled: '#C7C4C2',
    },
    Table: {
      colorBgContainer: '#fff',
      headerColor: '#383533',
      headerBorderRadius: 10,
      cellPaddingInlineMD: 12,
      footerColor: '#fff',
      headerSplitColor: '#F0EEEC',
      headerBg: '#F9F7F1',
      colorText: '#61605F',
      selectionColumnWidth: 50,
      rowHoverBg: '#fafafa',
      rowSelectedBg: '#fafafa',
      rowSelectedHoverBg: '#fafafa',
    },
    Pagination: {
      itemActiveBg: '#CCAC85',
      itemSize: 28,
      borderRadius: 2,
      colorPrimary: '#CCAC85',
      fontWeightStrong: 400,
      colorText: '#969390',
      itemInputBg: '#fff',
      marginXS: 6,
    },
    Modal: {
      contentBg: '#fff',
      headerBg: '#fff',
      titleFontSize: 16,
    },
    Segmented: {
      trackBg: '#f3f3f3',
      itemSelectedColor: '#AA754D',
      itemColor: '#969390',
      itemSelectedBg: '#fff',
    },
    Input: {
      controlHeightLG: 36,
      controlHeight: 32,
      controlHeightSM: 28,
      colorText: '#61605F',
      colorBgContainerDisabled: '#F3F3F3',
      colorTextDisabled: '#61605F',
      borderRadiusLG: 6,
      borderRadius: 6,
      borderRadiusSM: 6,
      inputFontSize: 14,
      inputFontSizeLG: 14,
      inputFontSizeSM: 14,
      colorBgContainer: '#fff',
    },
    InputNumber: {
      controlHeightLG: 36,
      controlHeight: 32,
      controlHeightSM: 28,
      colorBgContainerDisabled: '#F3F3F3',
      colorTextDisabled: '#61605F',
      borderRadiusLG: 6,
      borderRadius: 6,
      borderRadiusSM: 6,
      inputFontSize: 14,
      inputFontSizeLG: 14,
      inputFontSizeSM: 14,
      colorBgContainer: '#fff',
    },
    Tooltip: {
      colorBgSpotlight: '#595959',
      paddingContentHorizontal: 16,
      paddingSM: 10,
    },
    DatePicker: {
      colorBgContainer: '#fff',
      colorBgContainerDisabled: '#F3F3F3',
      colorTextDisabled: '#61605F',
      borderRadiusLG: 6,
      borderRadius: 6,
      borderRadiusSM: 6,
      inputFontSize: 14,
      inputFontSizeLG: 14,
      inputFontSizeSM: 14,
    },
    Form: {
      itemMarginBottom: 18,
      verticalLabelPadding: '0 0 4px',
    },
  },
};
