name: Release

on:
  push:
    tags:
      - 'v*'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Upload ZIP Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.UPLOADRELEASEASSET }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/page-query-text-v1.0.zip
          asset_name: page-query-text-v1.0.zip
          asset_content_type: application/zip